/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.RegistroMedico;
import model.RegistroMedicoTableModel;




public class FormRegistroMedico extends javax.swing.JFrame {

    RegistroMedicoTableModel tablemodel = new RegistroMedicoTableModel(); // instanciando uma classe
    String pathFile = "db.txt";
    String pathFileTemp = "dbTemp.txt";
    String readFile = "";
    
    List <RegistroMedico> listRegistroMedico = new ArrayList<>();
    private final TableRowSorter<TableModel> sorter = new TableRowSorter<>(tablemodel);
    
    
    public FormRegistroMedico() {
        initComponents();
        //Centralizando a janela
        this.setLocationRelativeTo(null);
        // Impede que a janela seja redimencionada 
        this.setResizable(false);
        // Trocando cursor para HAND CURSOR(Maozinha)
        // jButtonRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        // Variavel con recebendo a conexao
        //carregarTable(null);

        
    }
    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbregmedico = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        btnAtualizar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNoRm = new javax.swing.JTextField();
        txtPaciente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtEndereco = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        txtClasse = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSala = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(102, 0, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Cadastro Sega 2022 EEEP MM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(208, 208, 208))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        tbregmedico.setForeground(new java.awt.Color(102, 0, 102));
        tbregmedico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "Email", "Endereco", "Tel", "Jogo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbregmedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbregmedicoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbregmedico);

        jPanel2.setBackground(new java.awt.Color(102, 0, 204));

        jLabel7.setForeground(new java.awt.Color(255, 255, 51));
        jLabel7.setText("Pesquisar:");

        txtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaActionPerformed(evt);
            }
        });
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });

        btnAtualizar.setForeground(new java.awt.Color(102, 0, 102));
        btnAtualizar.setText("Buscar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnDeletar.setForeground(new java.awt.Color(102, 0, 102));
        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        btnSalvar.setForeground(new java.awt.Color(102, 0, 102));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAtualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeletar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtualizar)
                    .addComponent(btnDeletar)
                    .addComponent(btnSalvar))
                .addGap(14, 14, 14))
        );

        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("Nome:");

        txtNoRm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoRmActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("Email:");

        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setText("Endereco:");

        txtEndereco.setColumns(20);
        txtEndereco.setRows(5);
        jScrollPane2.setViewportView(txtEndereco);

        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setText("Telefone:");

        txtClasse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClasseKeyTyped(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(102, 0, 102));
        jLabel6.setText("Jogo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(txtNoRm))
                                .addGap(132, 132, 132)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtClasse)
                                    .addComponent(txtSala)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtClasse)
                        .addComponent(jLabel5))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtNoRm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSala)
                        .addComponent(jLabel6))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
try {
            Deletar();
            limpardados();
            AtualizacaoDoRegistroMedico();
            btnDeletar.setEnabled(false);
            btnSalvar.setText("Salvar");
            dialog("Dado Deletado");
        } catch (IOException e) {
          //  JOptionPane.showMessageDialog(null, e);
        }
                // TODO add your handling code here:
            
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased
        
    }//GEN-LAST:event_txtPesquisaKeyReleased

    private void tbregmedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbregmedicoMouseClicked
        int click = tbregmedico.rowAtPoint(evt.getPoint());
        txtNoRm.setText(tbregmedico.getModel().getValueAt(click, 0).toString().replace("ReM-", ""));
        txtPaciente.setText((String) tbregmedico.getModel().getValueAt(click, 1));
        txtEndereco.setText((String) tbregmedico.getModel().getValueAt(click, 2));
        txtSala.setText(tbregmedico.getModel().getValueAt(click, 3).toString());
        txtClasse.setText((String) tbregmedico.getModel().getValueAt(click, 4));
        btnSalvar.setText("Salvar");
        btnDeletar.setEnabled(true);
        // TODO add your handling code here:
       
    }//GEN-LAST:event_tbregmedicoMouseClicked

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        limpardados();
        btnDeletar.setEnabled(false);
        try {
            // btnSimpan.setText("Atualizar");
            AtualizacaoDoRegistroMedico();
            // TODO add your handling code here:
            // btnSimpan.setText("Atualizar");
        } catch (IOException ex) {
            Logger.getLogger(FormRegistroMedico.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void txtClasseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClasseKeyTyped
        
    }//GEN-LAST:event_txtClasseKeyTyped

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
SalvarAtualizar();     // TODO add your handling code here:
   
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
   
    }//GEN-LAST:event_txtPesquisaActionPerformed

    private void txtNoRmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoRmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoRmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRegistroMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbregmedico;
    private javax.swing.JTextField txtClasse;
    private javax.swing.JTextArea txtEndereco;
    private javax.swing.JTextField txtNoRm;
    private javax.swing.JTextField txtPaciente;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField txtSala;
    // End of variables declaration//GEN-END:variables

private void limpardados(){
        txtNoRm.setText("");
        txtPaciente.setText("");
        txtEndereco.setText("");
        txtClasse.setText("");
        txtSala.setText("");
        txtPesquisa.setText("");
    }
private void mostrardados() {
        try {
            listRegistroMedico.clear();
            String readLine;
            File file = new File(pathFile);
            if (!file.exists()) {
                file.createNewFile();
            }
                     
            BufferedReader bufReader;
            try (FileReader reader = new FileReader(file)) {
                bufReader = new BufferedReader(reader);
           
              while ((readLine = bufReader.readLine()) != null) {
                    if (readLine.equals("")) {
                        continue;
                    }
                    String[] splitData = readLine.split(";");
                    RegistroMedico rm = new RegistroMedico();
                    rm.setRm(splitData[0]);
                    rm.setPaciente(splitData[1]);
                    rm.setEndereco(splitData[2]);
                    rm.setClasse(Integer.parseInt(splitData[3]));
                    rm.setSala(splitData[4]);
                    listRegistroMedico.add(rm);
                }
             
                tablemodel.setList(listRegistroMedico);
                tbregmedico.setModel(tablemodel);
            }
            bufReader.close();
        } catch (IOException ex) {
            Logger.getLogger(FormRegistroMedico.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
private void AtualizacaoDoRegistroMedico() throws IOException {
        String ID, record2;
        File db = new File(pathFile);
        File tempDB = new File(pathFileTemp);
        BufferedReader br2;
        try (BufferedWriter bw = new BufferedWriter(new FileWriter(tempDB))) {
            ID = "RM-"+txtNoRm.getText();
            br2 = new BufferedReader(new FileReader(db));
            while ((record2 = br2.readLine()) != null) {
                if (record2.contains(ID)) {
                    bw.write("RM-"+txtNoRm.getText()+";" + txtPaciente.getText() + ";" + txtEndereco.getText() + ";" + txtClasse.getText() + ";" + txtSala.getText());
                } else {
                    bw.write(record2);
                }
                bw.flush();
                bw.newLine();
            }
        }
        br2.close();
        db.delete();
        tempDB.renameTo(db);
    }

private void dialog(String text){
        JOptionPane.showMessageDialog(rootPane, text);
    }
private void SalvarAtualizar(){
        if (btnSalvar.getText().equals("Salvar")) {
            String save = "\n" + "RM-" + txtNoRm.getText() + ";" + txtPaciente.getText() + ";" + txtEndereco.getText() + ";" + txtClasse.getText() + ";" + txtSala.getText();
            try (BufferedWriter bw = new BufferedWriter(new FileWriter(pathFile, true))) {
                bw.write(save);
                bw.flush();
                bw.newLine();
                bw.close();
                limpardados();
                mostrardados();
                dialog("Dados salvos com sucesso");
            } catch (IOException e) {
            }
        } else {
            try {
                AtualizacaoDoRegistroMedico();
                limpardados();
                mostrardados();
                btnDeletar.setEnabled(false);
                btnSalvar.setText("Salvar");
                dialog("Dados alterados com sucesso");
            } catch (IOException e) {
            }
        }
    }




private void Deletar() throws IOException {

        String ID, record;
        File tempDB = new File(pathFileTemp);
        File db = new File(pathFile);
        BufferedWriter bw;
        try (BufferedReader br = new BufferedReader(new FileReader(db))) {
            bw = new BufferedWriter(new FileWriter(tempDB));
            ID = "RM-"+txtNoRm.getText();
            while ((record = br.readLine()) != null) {
                if (record.contains(ID)) {
                    continue;
                }
                bw.write(record);
                bw.flush();
                bw.newLine();
            }
        }
        bw.close();
        db.delete();
        tempDB.renameTo(db);
    }
    
private void logicaClasse(){
       if (txtClasse.getText().isEmpty()&&txtEndereco.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Não foi digitada a especialidade médica");
       }
       else{ 
        switch (Integer.parseInt(txtClasse.getText())) {
            case 1:
                txtSala.setText("CARDIOLOGISTA");
                break;
            case 2:
                txtSala.setText("ORTOPEDISTA");
                break;
            default:
                txtSala.setText("CLINICO GERAL");
                break;
        }
       }
}






}
